Repository pivotal-cf/docs-pcf-healthwatch, pull requests merged in 2018-09, with the labels that each got.

#150 fix broken markdown link [#160266686]
  metrics.html.md.erb
Labels: unscheduled

#151 fix broken markdown link [#160266686]
  metrics.html.md.erb
Labels: unscheduled

#152 fix broken markdown link [#160266686]
  metrics.html.md.erb
Labels: unscheduled

#153 Added new Category column to alerts table [#160399765]
  api/alerts.html.md.erb
Labels: unscheduled

#149 Add missing alerts
  api/alerts.html.md.erb
Labels: scheduled

#148 Add missing alerts
  api/alerts.html.md.erb
Labels: scheduled

#154 documentation for querying free chunks with promql/logcache [#159469622]
  metrics.html.md.erb
  using.html.md.erb
Labels: unscheduled

#155 documentation for querying free chunks with promql/logcache [#159469622]
  metrics.html.md.erb
  using.html.md.erb
Labels: unscheduled

#157 clarify bosh deployment check installation instrucionts [#159664124]
  installing.html.md.erb
Labels: unscheduled

#158 clarify bosh deployment check installation instrucionts [#159664124]
  installing.html.md.erb
Labels: in progress

#147 Add missing alerts
  api/alerts.html.md.erb
Labels: scheduled

#160 add networking configuration [#157138398]
  architecture.html.md.erb
Labels: unscheduled

#164 Correcting indentation issue
  using.html.md.erb
Labels: unscheduled

#166 Adds an example SLI query for canary app availability [#158378094]
  using.html.md.erb
Labels: unscheduled

#163 add networking configuration [#157138398]
  architecture.html.md.erb
Labels: unscheduled

#162 add networking configuration [#157138398]
  architecture.html.md.erb
Labels: unscheduled

#161 add networking configuration [#157138398]
  architecture.html.md.erb
Labels: unscheduled

#159 add SLI section to metrics.html [#160633414]
  metrics.html.md.erb
Labels: in progress

#167 Pulls promQL examples from 1.4 docs [#158378094]
  using.html.md.erb
Labels: unscheduled

#168 Adds SLI section to platform metrics page [#160633414]
  metrics.html.md.erb
Labels: unscheduled
