Repository pivotal-cf/docs-pcf-healthwatch, pull requests merged in 2019-02, with the labels that each got.

#206 update 1.4 compatibility matrix docs to reflect supporting 2.4.x pcf
  index.html.md.erb
Labels: unscheduled

#201 Add 2.4 cf hardcode change known issue to the release notes
  release-notes.html.md.erb
Labels: in progress

#208 document change of the default activelocks threshold to 5
  release-notes.html.md.erb
Labels: scheduled

#209 Update 1.5 HAPI docs to handle cf hardcode changes
  api/canary-configuration.html.md.erb
Labels: scheduled

#210 update the hapi curl example to use uaac curl instead [#163953645]
  api/alerts.html.md.erb
  api/canary-configuration.html.md.erb
  api/free-chunks.html.md.erb
  using.html.md.erb
Labels: scheduled

#211 update the hapi curl example to use uaac curl instead [#163953645]
  api/alerts.html.md.erb
  api/canary-configuration.html.md.erb
  api/free-chunks.html.md.erb
  using.html.md.erb
Labels: scheduled

#214 Update 1.3.3 release notes
  index.html.md.erb
  release-notes.html.md.erb
Labels: scheduled

#213 Update release docs for healthwatch v1.4.5 [#163829027]
  index.html.md.erb
  release-notes.html.md.erb
Labels: scheduled

#216 Update docs to healthwatch version 1.3.4
  index.html.md.erb
Labels: unscheduled

#221 Add browser support section to index page
  index.html.md.erb
Labels: scheduled

#222 Add browser support section to index page
  index.html.md.erb
Labels: scheduled
