Repository pivotal-cf/docs-pcf-healthwatch, pull requests merged in 2019-03, with the labels that each got.

#218 updates docs for 1.5
  release-notes.html.md.erb
Labels: in progress

#224 Add browser support section to index page
  index.html.md.erb
Labels: scheduled

#223 Add browser support section to index page
  index.html.md.erb
Labels: scheduled

#219 updates docs for 1.3
  installing.html.md.erb
Labels: scheduled

#217 updates docs for 1.4
  installing.html.md.erb
  release-notes.html.md.erb
Labels: scheduled

#231 Remove version specific links where possible and use 1.2 otherwise
  architecture.html.md.erb
  monitoring.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
Labels: scheduled

#230 Remove version specific links where possible and use 1.3 otherwise
  architecture.html.md.erb
  monitoring.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
Labels: scheduled

#229 Remove version specific links where possible and use 1.5 otherwise
  architecture.html.md.erb
  installing.html.md.erb
  monitoring.html.md.erb
  resources.html.md.erb
Labels: scheduled

#228 Remove version specific links where possible and use 1.4 otherwise
  architecture.html.md.erb
  monitoring.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
Labels: scheduled

#227 Add CF CLI test run requirements section
  architecture.html.md.erb
Labels: scheduled

#226 Add CF CLI test run requirements section
  architecture.html.md.erb
Labels: scheduled

#225 Update active locks threshold to 5
  api/alerts.html.md.erb
Labels: scheduled

#235 Update worker and ingestor scaling recommendations for 1.5
  installing.html.md.erb
  resources.html.md.erb
Labels: in progress

#234 Update worker and ingestor scaling recommendations for 1.4
  installing.html.md.erb
  resources.html.md.erb
Labels: scheduled

#233 Update worker and ingestor scaling recommendations for 1.3
  installing.html.md.erb
  resources.html.md.erb
Labels: scheduled

#232 Update worker and ingestor scaling recommendations for 1.2
  installing.html.md.erb
  resources.html.md.erb
Labels: scheduled

#243 Fix log-cache examples
  using.html.md.erb
Labels: scheduled

#242 Fix log-cache examples
  using.html.md.erb
Labels: scheduled

#241 Fix typo and update doc on Canary App metrics
  metrics.html.md.erb
Labels: scheduled

#239 Fix typo and update doc on Canary App metrics
  metrics.html.md.erb
Labels: scheduled

#240 Fix typo and update doc on Canary App metrics
  metrics.html.md.erb
Labels: scheduled

#238 document known issue for vsan [#164664689]
  release-notes.html.md.erb
Labels: in progress

#244 Update 1.5 docs for 1.5.2 release
  index.html.md.erb
  release-notes.html.md.erb
Labels: scheduled

#245 include specific link for log cache duration KPIs [#164967049]
  release-notes.html.md.erb
Labels: unscheduled
