Repository pivotal-cf/docs-pcf-healthwatch, pull requests merged in 2019-09, with the labels that each got.

#300 Fixing Typo
  indicator-protocol.html.md.erb
Labels: scheduled

#303 1.4.9
  index.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
Labels: unscheduled

#304 Release notes for 1.6.2
  api/alerts.html.md.erb
  index.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
Labels: unscheduled

#305 changing 1.6.2 to 1.6.3 [#168483212]
  index.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#306 docs about new user [#164158338]
  architecture.html.md.erb
Labels: unscheduled

#289 update the threshold for syslog drain bindings
  api/alerts.html.md.erb
Labels: scheduled

#298 update cf to cf-guid in canary docs
  api/canary-configuration.html.md.erb
Labels: scheduled

#290 Release notes branch for HW 1.7.0
  images/dashboard-all-green.png
  index.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
Labels: scheduled

#301 1.7 alert change 167710822
  api/alerts.html.md.erb
Labels: scheduled

#302 Update PCF Healthwatch to Pivotal Healthwatch [#168276879]
  api/alerts.html.md.erb
  api/canary-configuration.html.md.erb
  api/free-chunks.html.md.erb
  api/index.html.md.erb
  architecture.html.md.erb
  images/healthwatch-architecture.graffle
  index.html.md.erb
  indicator-protocol.html.md.erb
  installing.html.md.erb
  metrics.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
  troubleshooting.html.md.erb
  using.html.md.erb
Labels: scheduled

#309 1.5.5 release notes & updates
  api/alerts.html.md.erb
  index.html.md.erb
  release-notes.html.md.erb
  resources.html.md.erb
Labels: unscheduled

#307 docs about new user [#164158338]
  architecture.html.md.erb
Labels: in progress

#308 update diego alert warning threshold [#166916763]
  api/alerts.html.md.erb
Labels: in progress
